import Foundation

/// One file of a model, as it is stored on disk and published upstream.
public struct ModelFile: Hashable, Codable, Sendable {
    /// Path relative to the model's directory, e.g.
    /// `streaming_encoder.mlmodelc/weights/weight.bin`.
    public let path: String
    /// Exact size in bytes.
    public let size: Int64
    /// Lowercase hex SHA-256 of the contents.
    public let sha256: String

    public init(path: String, size: Int64, sha256: String) {
        self.path = path
        self.size = size
        self.sha256 = sha256
    }
}

/// A model pinned to one immutable upstream revision, with every file it
/// needs.
///
/// Pinning a commit (never a branch) and checking every file's SHA-256 means
/// a build of Blau always runs exactly the weights it was tested with, even
/// if the upstream repository moves on.
public struct ModelDescriptor: Hashable, Identifiable, Sendable {
    public let id: ModelID
    /// Hugging Face repository, `owner/name`.
    public let repository: String
    /// Full commit SHA the files are fetched from.
    public let revision: String
    /// Directory inside the repository that holds the model, or `""` for the
    /// root. It is not part of the local path.
    public let remoteDirectory: String
    /// Every file, sorted by path.
    public let files: [ModelFile]

    public init(id: ModelID, repository: String, revision: String, remoteDirectory: String, files: [ModelFile]) {
        self.id = id
        self.repository = repository
        self.revision = revision
        self.remoteDirectory = remoteDirectory
        self.files = files.sorted { $0.path < $1.path }
    }

    /// Total download size in bytes.
    public var totalBytes: Int64 { files.reduce(0) { $0 + $1.size } }

    /// Names of the compiled Core ML bundles (`*.mlmodelc`) at the top of
    /// the model directory, sorted. These are what warm-up loads.
    public var bundles: [String] {
        let names = files.compactMap { file -> String? in
            guard let first = file.path.split(separator: "/").first, first.hasSuffix(".mlmodelc") else { return nil }
            return String(first)
        }
        return Set(names).sorted()
    }

    /// The download URL of `file` at the pinned revision.
    ///
    /// - Parameter host: The model registry, `https://huggingface.co` by
    ///   default. A mirror must serve the same `resolve/<revision>/<path>`
    ///   layout.
    public func remoteURL(for file: ModelFile, host: URL = ModelDescriptor.defaultHost) -> URL {
        let remotePath = remoteDirectory.isEmpty ? file.path : "\(remoteDirectory)/\(file.path)"
        return
            host
            .appending(path: repository, directoryHint: .isDirectory)
            .appending(path: "resolve", directoryHint: .isDirectory)
            .appending(path: revision, directoryHint: .isDirectory)
            .appending(path: remotePath, directoryHint: .notDirectory)
    }

    /// Hugging Face.
    public static let defaultHost = URL(string: "https://huggingface.co")!
}

/// The set of models a build of Blau uses. The production manifest is
/// ``pinned``, generated by `scripts/update-model-manifest.py`.
public struct ModelManifest: Hashable, Sendable {
    /// Models in download order: required first, in ``ModelID`` order.
    public let models: [ModelDescriptor]

    public init(models: [ModelDescriptor]) {
        precondition(Set(models.map(\.id)).count == models.count, "A model appears twice in the manifest")
        let order = Dictionary(uniqueKeysWithValues: ModelID.allCases.enumerated().map { ($1, $0) })
        self.models = models.sorted { lhs, rhs in
            if lhs.id.isRequired != rhs.id.isRequired { return lhs.id.isRequired }
            return order[lhs.id, default: 0] < order[rhs.id, default: 0]
        }
    }

    public subscript(id: ModelID) -> ModelDescriptor? {
        models.first { $0.id == id }
    }

    /// The models Blau can't listen without.
    public var required: [ModelDescriptor] { models.filter(\.id.isRequired) }

    /// The models that only improve quality.
    public var optional: [ModelDescriptor] { models.filter { !$0.id.isRequired } }
}
