// Generated by scripts/update-model-manifest.py. Do not edit by hand:
// change the pins in the script and run it again. See docs/models.md.

extension ModelManifest {
    /// The models this build of Blau downloads, each pinned to an
    /// immutable Hugging Face commit with per-file sizes and SHA-256s.
    public static let pinned = ModelManifest(models: [
        // FluidInference/silero-vad-coreml@b419383c55c1: 5 files, 1,063,425 bytes
        ModelDescriptor(
            id: .sileroVAD,
            repository: "FluidInference/silero-vad-coreml",
            revision: "b419383c55c110e2c9271fa6ee0ea83d03c70d96",
            remoteDirectory: "",
            files: [
                ModelFile(
                    path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "8067594eb3126ab8318af507f0c00cabfed40d5fedb8a0ee5075dd02e903d909"
                ),
                ModelFile(
                    path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/coremldata.bin",
                    size: 625,
                    sha256: "7db35a4fd995222a7fb0129713473b15d1462572ab4a2e5e4d56bcaad9e40f41"
                ),
                ModelFile(
                    path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/metadata.json",
                    size: 3335,
                    sha256: "2740be542c611e1ba358e1849b4e265c65cdf0b17192767e1e5de86a31ac94d6"
                ),
                ModelFile(
                    path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/model.mil",
                    size: 176918,
                    sha256: "c6a9d1bf22d413265da0a07a1d14151c3ea2fad296b3aa5859275b33ef1c3270"
                ),
                ModelFile(
                    path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/weights/weight.bin",
                    size: 882304,
                    sha256: "53ecc8b5081146140ab654c89109cf001f2183abddd7a2411c5081feeffff063"
                ),
            ]
        ),
        // FluidInference/parakeet-realtime-eou-120m-coreml@40a23f4c0b33 (320ms): 16 files, 224,238,270 bytes
        ModelDescriptor(
            id: .parakeetRealtimeEOU,
            repository: "FluidInference/parakeet-realtime-eou-120m-coreml",
            revision: "40a23f4c0b333aa17ad8c0f2ea47ec2347f2f355",
            remoteDirectory: "320ms",
            files: [
                ModelFile(
                    path: "decoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "3996975a8cbc1949159c55605b3132b39b2484f51acbd55d796d93c70de02b49"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/coremldata.bin",
                    size: 497,
                    sha256: "c3ccbff963d8cf07e2be2bd56ea3384a89ea49628922c6bd95ff62e2ae57dc34"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/metadata.json",
                    size: 3283,
                    sha256: "0977480649f2756894b0acfe2fdf4231a991f25e3fe02562bfb71b65ca944575"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/model.mil",
                    size: 7409,
                    sha256: "b7c084a35bdbc887d69d6226cd533e2c11b2792c37d7352cf878f9f6f3c13555"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/weights/weight.bin",
                    size: 7_873_600,
                    sha256: "0b4cacecdcd9df79ab1e56de67230baf5a8664d2afe0bb8f3408eefa972cb2f4"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "5bca32ad130dcad6605cc00044c752aa5b45ef57d14c17f2d1a2fa49d6cf55b5"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/coremldata.bin",
                    size: 493,
                    sha256: "22d4abc4625b935ee035b5f8ce7cb28d1041b9b01c12173e287bf4b5f5d99625"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/metadata.json",
                    size: 3181,
                    sha256: "e970ae87137730020690d24d971813db3633bbdfed602d43b6a9c84deced6dc8"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/model.mil",
                    size: 9608,
                    sha256: "45e8590bc87e34c162b547e43a4f60e64db15b017f48395d7835a6867884804f"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/weights/weight.bin",
                    size: 2_794_182,
                    sha256: "7039b2010a269153f5a96edf28637f921a86ef8822f248f2d6712f7a6bce84b4"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "ae0a559f8d53c43fe13c5c142b15ca237b97812febde71a36475b7b9612baec5"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/coremldata.bin",
                    size: 670,
                    sha256: "b57dfe32ed2acb0081f97d7a9e410117005823e3d2d995e21feb9e60775443c3"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/metadata.json",
                    size: 5327,
                    sha256: "3adc7839db0f5d20b19e2dcd1c009bcf935a7edc61d7473c8150be444bd80488"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/model.mil",
                    size: 655998,
                    sha256: "eb9d56d7467ad3a8796ec9098b27fb89197638b31e24ede6dd924807d25086e6"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/weights/weight.bin",
                    size: 212_865_856,
                    sha256: "ff553fcb4f4560cfce1e558e16bb9d856e4b4f6a4c08f800d5c126fce4196822"
                ),
                ModelFile(
                    path: "vocab.json",
                    size: 17437,
                    sha256: "83fd42ad33dae1bd3ceee6c0bb6c625f314cf0b2dc8430be441ac1e2643d5c36"
                ),
            ]
        ),
        // FluidInference/parakeet-tdt-0.6b-v3-coreml@7dd20fe6b179: 21 files, 483,105,645 bytes
        ModelDescriptor(
            id: .parakeetTDTv3,
            repository: "FluidInference/parakeet-tdt-0.6b-v3-coreml",
            revision: "7dd20fe6b1797d35f5e3307e8b1732d9a178edfe",
            remoteDirectory: "",
            files: [
                ModelFile(
                    path: "Decoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "4238c4e81ecd0dc94bd7dfbb60f7e2cc824107c1ffe0387b8607b72833dba350"
                ),
                ModelFile(
                    path: "Decoder.mlmodelc/coremldata.bin",
                    size: 554,
                    sha256: "18647af085d87bd8f3121c8a9b4d4564c1ede038dab63d295b4e745cf2d7fb99"
                ),
                ModelFile(
                    path: "Decoder.mlmodelc/metadata.json",
                    size: 3427,
                    sha256: "a39e93cd8371b8ded92635c7804fcd0590f0d1dd9415c6d19a0484be073077d9"
                ),
                ModelFile(
                    path: "Decoder.mlmodelc/model.mil",
                    size: 13110,
                    sha256: "ef2a0a281695398a62fde86ac269c68f73d5b578d7ed3b31f2ba91a2d1ea1f35"
                ),
                ModelFile(
                    path: "Decoder.mlmodelc/weights/weight.bin",
                    size: 23_604_992,
                    sha256: "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41"
                ),
                ModelFile(
                    path: "Encoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "42e638870d73f26b332918a3496ce36793fbb413a81cbd3d16ba01328637a105"
                ),
                ModelFile(
                    path: "Encoder.mlmodelc/coremldata.bin",
                    size: 485,
                    sha256: "d48034a167a82e88fc3df64f60af963ab3983538271175b8319e7d5720a0fb86"
                ),
                ModelFile(
                    path: "Encoder.mlmodelc/metadata.json",
                    size: 2921,
                    sha256: "da24da9cca943fb29d7fa8e376d57fca7cb3aa08ca51b956b0b0e56813f087e9"
                ),
                ModelFile(
                    path: "Encoder.mlmodelc/model.mil",
                    size: 959769,
                    sha256: "ed7b19156ca29fa7dfd6891deb9fda4b0e8893f68597c985d135736546a43808"
                ),
                ModelFile(
                    path: "Encoder.mlmodelc/weights/weight.bin",
                    size: 445_187_200,
                    sha256: "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421"
                ),
                ModelFile(
                    path: "JointDecisionv3.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "26def4bf73dd56d29dee21c8ef97cb8969e62f6120ed1adc91e46828e2737b6c"
                ),
                ModelFile(
                    path: "JointDecisionv3.mlmodelc/coremldata.bin",
                    size: 521,
                    sha256: "f5fc08b741400f0088492c9e839418b1e18522f19cba28d361dd030c5f398342"
                ),
                ModelFile(
                    path: "JointDecisionv3.mlmodelc/metadata.json",
                    size: 3453,
                    sha256: "d9307211b9a37e0f0ac260c7660b1571a3de25841035cfdf9b58fd40425f890f"
                ),
                ModelFile(
                    path: "JointDecisionv3.mlmodelc/model.mil",
                    size: 11775,
                    sha256: "be60732943389a047175111a83f8839f3eb39d4803adafa828a0871b2f39818d"
                ),
                ModelFile(
                    path: "JointDecisionv3.mlmodelc/weights/weight.bin",
                    size: 12_642_764,
                    sha256: "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e"
                ),
                ModelFile(
                    path: "Preprocessor.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "c9beeb989c8d66f8be11df59bc6df277ec76cee404f6865b46243835ef562f6d"
                ),
                ModelFile(
                    path: "Preprocessor.mlmodelc/coremldata.bin",
                    size: 486,
                    sha256: "dbde3f2300842c1fd51ef3ff948a0bcffe65ffd2dca10707f2509f32c1d65b1d"
                ),
                ModelFile(
                    path: "Preprocessor.mlmodelc/metadata.json",
                    size: 2841,
                    sha256: "2a98699e22d279dd37fa1d238aeb1c6db1df0d6fad687775324157689d8f3acf"
                ),
                ModelFile(
                    path: "Preprocessor.mlmodelc/model.mil",
                    size: 28181,
                    sha256: "4b8518a956450fec57f06c2a21bdffc26973f7f1fa6842fb38fe917f896b6b93"
                ),
                ModelFile(
                    path: "Preprocessor.mlmodelc/weights/weight.bin",
                    size: 491072,
                    sha256: "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea"
                ),
                ModelFile(
                    path: "parakeet_vocab.json",
                    size: 151122,
                    sha256: "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735"
                ),
            ]
        ),
        // FluidInference/parakeet-realtime-eou-120m-coreml@40a23f4c0b33 (1280ms): 16 files, 224,525,706 bytes
        ModelDescriptor(
            id: .parakeetRealtimeEOU1280,
            repository: "FluidInference/parakeet-realtime-eou-120m-coreml",
            revision: "40a23f4c0b333aa17ad8c0f2ea47ec2347f2f355",
            remoteDirectory: "1280ms",
            files: [
                ModelFile(
                    path: "decoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "3996975a8cbc1949159c55605b3132b39b2484f51acbd55d796d93c70de02b49"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/coremldata.bin",
                    size: 497,
                    sha256: "c3ccbff963d8cf07e2be2bd56ea3384a89ea49628922c6bd95ff62e2ae57dc34"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/metadata.json",
                    size: 3283,
                    sha256: "0977480649f2756894b0acfe2fdf4231a991f25e3fe02562bfb71b65ca944575"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/model.mil",
                    size: 7409,
                    sha256: "b7c084a35bdbc887d69d6226cd533e2c11b2792c37d7352cf878f9f6f3c13555"
                ),
                ModelFile(
                    path: "decoder.mlmodelc/weights/weight.bin",
                    size: 7_873_600,
                    sha256: "0b4cacecdcd9df79ab1e56de67230baf5a8664d2afe0bb8f3408eefa972cb2f4"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "5bca32ad130dcad6605cc00044c752aa5b45ef57d14c17f2d1a2fa49d6cf55b5"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/coremldata.bin",
                    size: 493,
                    sha256: "22d4abc4625b935ee035b5f8ce7cb28d1041b9b01c12173e287bf4b5f5d99625"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/metadata.json",
                    size: 3181,
                    sha256: "e970ae87137730020690d24d971813db3633bbdfed602d43b6a9c84deced6dc8"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/model.mil",
                    size: 9608,
                    sha256: "45e8590bc87e34c162b547e43a4f60e64db15b017f48395d7835a6867884804f"
                ),
                ModelFile(
                    path: "joint_decision.mlmodelc/weights/weight.bin",
                    size: 2_794_182,
                    sha256: "7039b2010a269153f5a96edf28637f921a86ef8822f248f2d6712f7a6bce84b4"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "d0a3c84022a9d2dc769d38cf8f45e93423e20734d092e3c16db11fbf6dca4004"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/coremldata.bin",
                    size: 671,
                    sha256: "41ce3f96c3d6b3333796fc4ed82cb0c9b4ea99396b88f8eec3ba24394ba2bb78"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/metadata.json",
                    size: 5331,
                    sha256: "32d0833f71105be72cb95d60861ce6fc133cb7cb674554954a70b9cb85ea1413"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/model.mil",
                    size: 630085,
                    sha256: "f22bdb1cade3771ed80b125d1e941fe836366c1c3390e0bed8f00cdcd3fb4976"
                ),
                ModelFile(
                    path: "streaming_encoder.mlmodelc/weights/weight.bin",
                    size: 213_179_200,
                    sha256: "6c71acb590ceb2af449de5c7e3516e76057eaf4589d1f16edba774831db74b17"
                ),
                ModelFile(
                    path: "vocab.json",
                    size: 17437,
                    sha256: "83fd42ad33dae1bd3ceee6c0bb6c625f314cf0b2dc8430be441ac1e2643d5c36"
                ),
            ]
        ),
        // FluidInference/speaker-diarization-coreml@df2625ac79a7: 5 files, 7,954,144 bytes
        ModelDescriptor(
            id: .speakerEmbedding,
            repository: "FluidInference/speaker-diarization-coreml",
            revision: "df2625ac79a7ac6b65ad868fee6d80f320da4232",
            remoteDirectory: "",
            files: [
                ModelFile(
                    path: "wespeaker_v2.mlmodelc/analytics/coremldata.bin",
                    size: 243,
                    sha256: "d2b1fcde6121aea3ff0e14c1dc50d09dacb0314a2e89156353c31804230a422f"
                ),
                ModelFile(
                    path: "wespeaker_v2.mlmodelc/coremldata.bin",
                    size: 359,
                    sha256: "6feb2472a71fa9d8a84020c85206138a4f6261c565c9884bf518d59dd5838da7"
                ),
                ModelFile(
                    path: "wespeaker_v2.mlmodelc/metadata.json",
                    size: 2738,
                    sha256: "ddc4858b4051254098015cd0b97080149839d697faf7b036f933190e70b26758"
                ),
                ModelFile(
                    path: "wespeaker_v2.mlmodelc/model.mil",
                    size: 706900,
                    sha256: "2850f775d6ba659f01f616fed77ce6a45a25de3eb7e4bf3a4b07b658be4e13dd"
                ),
                ModelFile(
                    path: "wespeaker_v2.mlmodelc/weights/weight.bin",
                    size: 7_243_904,
                    sha256: "34004f6798d35cad7071e2fdc67e63faaa782f53697e1cb49bcb452cf81ae151"
                ),
            ]
        ),
    ])
}
