#!/bin/sh
# write-secrets-xcconfig.sh: create Config/Secrets.xcconfig.
#
# CI: writes the file from the XAI_DEV_API_KEY environment variable, which a
# GitHub Actions workflow maps from a repository secret:
#
#   - run: scripts/write-secrets-xcconfig.sh
#     env:
#       XAI_DEV_API_KEY: ${{ secrets.XAI_DEV_API_KEY }}
#
# The secret is optional. Unit and UI tests are hermetic and never use it, so
# an unset or empty secret writes an empty key and the build still succeeds.
# Never set it for Release, TestFlight or App Store jobs: Release builds fail
# while XAI_DEV_API_KEY is non-empty.
#
# Locally (`make secrets`): with XAI_DEV_API_KEY unset, an existing
# Secrets.xcconfig is left alone and a missing one is copied from
# Secrets.example.xcconfig.
#
# Usage: scripts/write-secrets-xcconfig.sh [output path]
#        (default: Config/Secrets.xcconfig next to this repository's scripts/)

set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
output="${1:-$repo_root/Config/Secrets.xcconfig}"
example="$repo_root/Config/Secrets.example.xcconfig"

if [ -z "${XAI_DEV_API_KEY+set}" ]; then
    if [ -f "$output" ]; then
        echo "write-secrets-xcconfig: $output already exists; leaving it unchanged."
    else
        cp "$example" "$output"
        echo "write-secrets-xcconfig: created $output from Secrets.example.xcconfig."
    fi
    exit 0
fi

key=$(printf '%s' "$XAI_DEV_API_KEY" | tr -d '[:space:]')

# An xcconfig value ends at a newline and "//" starts a comment; a real key
# contains neither, so anything else is a malformed secret.
case "$key" in
    *//* | *'$('* | *'"'*)
        echo "error: XAI_DEV_API_KEY contains characters that are not valid in an xcconfig value." >&2
        exit 1
        ;;
esac

umask 077
{
    echo "// Generated by scripts/write-secrets-xcconfig.sh. Do not commit."
    echo "XAI_DEV_API_KEY = $key"
} >"$output"

if [ -n "$key" ]; then
    echo "write-secrets-xcconfig: wrote $output (XAI_DEV_API_KEY: ${#key} characters)."
else
    echo "write-secrets-xcconfig: wrote $output (XAI_DEV_API_KEY empty)."
fi
