#!/bin/sh
# write-secrets-xcconfig.sh: create Config/Secrets.xcconfig.
#
# CI does not need the key: tests are hermetic and never call xAI, and a
# missing Secrets.xcconfig is fine (#include?). CI test jobs must leave it
# unset, either by skipping this script or by writing the empty template:
#
#   - run: env -u XAI_DEV_API_KEY scripts/write-secrets-xcconfig.sh
#
# Do NOT map secrets.XAI_DEV_API_KEY into a job that uploads artifacts. While
# the key is set, Xcode copies it in clear text into the Debug .app's
# Info.plist, DerivedData, and the build log and .xcresult bundle of any run
# script phase that logs its environment. GitHub masks secrets in console
# output but not inside uploaded artifacts. A job that does set the key must
# never upload .xcresult bundles, build logs, DerivedData, .app or .ipa files,
# and must never be a Release, TestFlight or App Store job (Release builds
# fail while XAI_DEV_API_KEY is non-empty). See docs/configuration.md.
#
# With XAI_DEV_API_KEY set (even empty), the file is (re)written from it with
# mode 0600. This script prints only the key's length, never the key.
#
# Locally (`make secrets`, which unsets XAI_DEV_API_KEY first): an existing
# Secrets.xcconfig is left alone and a missing one is copied from
# Secrets.example.xcconfig.
#
# Usage: scripts/write-secrets-xcconfig.sh [output path]
#        (default: Config/Secrets.xcconfig next to this repository's scripts/)

set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
output="${1:-$repo_root/Config/Secrets.xcconfig}"
example="$repo_root/Config/Secrets.example.xcconfig"

if [ -z "${XAI_DEV_API_KEY+set}" ]; then
    if [ -f "$output" ]; then
        echo "write-secrets-xcconfig: $output already exists; leaving it unchanged."
    else
        cp "$example" "$output"
        echo "write-secrets-xcconfig: created $output from Secrets.example.xcconfig."
    fi
    exit 0
fi

key=$(printf '%s' "$XAI_DEV_API_KEY" | tr -d '[:space:]')

# An xcconfig value ends at a newline and "//" starts a comment; a real key
# contains neither, so anything else is a malformed secret.
case "$key" in
    *//* | *'$('* | *'"'*)
        echo "error: XAI_DEV_API_KEY contains characters that are not valid in an xcconfig value." >&2
        exit 1
        ;;
esac

umask 077
{
    echo "// Generated by scripts/write-secrets-xcconfig.sh. Do not commit."
    echo "XAI_DEV_API_KEY = $key"
} >"$output"
# umask only applies to a new file; tighten one that already existed.
chmod 600 "$output"

if [ -n "$key" ]; then
    echo "write-secrets-xcconfig: wrote $output (XAI_DEV_API_KEY: ${#key} characters)."
    echo "warning: Xcode copies XAI_DEV_API_KEY into the Debug .app, DerivedData and script-phase build logs (.xcresult). Never upload or share those from this machine or CI job. See docs/configuration.md." >&2
else
    echo "write-secrets-xcconfig: wrote $output (XAI_DEV_API_KEY empty)."
fi
